CREATE TABLE [dbo].[PELICULA]
(
[ID_PELICULA] [int] NOT NULL,
[ESTADO_RESERVA] [datetime] NULL,
[NOMBRE_PELICULA] [text] COLLATE Modern_Spanish_CI_AS NULL,
[FECHA_ESTRENO] [datetime] NULL
) ON [PRIMARY] TEXTIMAGE_ON [PRIMARY]
GO
ALTER TABLE [dbo].[PELICULA] ADD CONSTRAINT [PK_PELICULA] PRIMARY KEY CLUSTERED  ([ID_PELICULA]) ON [PRIMARY]
GO
CREATE NONCLUSTERED INDEX [RELATIONSHIP_11_FK] ON [dbo].[PELICULA] ([ESTADO_RESERVA]) ON [PRIMARY]
GO
ALTER TABLE [dbo].[PELICULA] ADD CONSTRAINT [FK_PELICULA_RELATIONS_HORA_DE_] FOREIGN KEY ([ESTADO_RESERVA]) REFERENCES [dbo].[HORA_DE_PELICULA] ([ESTADO_RESERVA])
GO
