CREATE TABLE [dbo].[EMPLEADO]
(
[ID_EMPLEADO] [int] NOT NULL,
[ID_CINE] [int] NULL,
[NOMBRE_EMPLEADO] [char] (150) COLLATE Modern_Spanish_CI_AS NULL,
[TELEFONO] [text] COLLATE Modern_Spanish_CI_AS NULL,
[DOMICILIO] [text] COLLATE Modern_Spanish_CI_AS NULL,
[CARGO] [text] COLLATE Modern_Spanish_CI_AS NULL,
[SALARIO] [decimal] (5, 2) NULL
) ON [PRIMARY] TEXTIMAGE_ON [PRIMARY]
GO
ALTER TABLE [dbo].[EMPLEADO] ADD CONSTRAINT [PK_EMPLEADO] PRIMARY KEY CLUSTERED  ([ID_EMPLEADO]) ON [PRIMARY]
GO
CREATE NONCLUSTERED INDEX [RELATIONSHIP_4_FK] ON [dbo].[EMPLEADO] ([ID_CINE]) ON [PRIMARY]
GO
ALTER TABLE [dbo].[EMPLEADO] ADD CONSTRAINT [FK_EMPLEADO_RELATIONS_CINE] FOREIGN KEY ([ID_CINE]) REFERENCES [dbo].[CINE] ([ID_CINE])
GO
