CREATE TABLE [dbo].[HORARIO]
(
[ID_HORARIO] [int] NOT NULL,
[ESTADO_RESERVA] [datetime] NULL,
[HORA_INICIO] [datetime] NULL,
[HORA_FIN] [datetime] NULL
) ON [PRIMARY]
GO
ALTER TABLE [dbo].[HORARIO] ADD CONSTRAINT [PK_HORARIO] PRIMARY KEY CLUSTERED  ([ID_HORARIO]) ON [PRIMARY]
GO
CREATE NONCLUSTERED INDEX [RELATIONSHIP_12_FK] ON [dbo].[HORARIO] ([ESTADO_RESERVA]) ON [PRIMARY]
GO
ALTER TABLE [dbo].[HORARIO] ADD CONSTRAINT [FK_HORARIO_RELATIONS_HORA_DE_] FOREIGN KEY ([ESTADO_RESERVA]) REFERENCES [dbo].[HORA_DE_PELICULA] ([ESTADO_RESERVA])
GO
