CREATE TABLE [dbo].[CINE_PELICULA]
(
[ID_CINEPELICULA] [int] NOT NULL,
[ID_CINE] [int] NULL,
[ID_PELICULA] [int] NULL
) ON [PRIMARY]
GO
ALTER TABLE [dbo].[CINE_PELICULA] ADD CONSTRAINT [PK_CINE_PELICULA] PRIMARY KEY CLUSTERED  ([ID_CINEPELICULA]) ON [PRIMARY]
GO
CREATE NONCLUSTERED INDEX [RELATIONSHIP_14_FK] ON [dbo].[CINE_PELICULA] ([ID_CINE]) ON [PRIMARY]
GO
CREATE NONCLUSTERED INDEX [RELATIONSHIP_15_FK] ON [dbo].[CINE_PELICULA] ([ID_PELICULA]) ON [PRIMARY]
GO
ALTER TABLE [dbo].[CINE_PELICULA] ADD CONSTRAINT [FK_CINE_PEL_RELATIONS_CINE] FOREIGN KEY ([ID_CINE]) REFERENCES [dbo].[CINE] ([ID_CINE])
GO
ALTER TABLE [dbo].[CINE_PELICULA] ADD CONSTRAINT [FK_CINE_PEL_RELATIONS_PELICULA] FOREIGN KEY ([ID_PELICULA]) REFERENCES [dbo].[PELICULA] ([ID_PELICULA])
GO
