CREATE TABLE [dbo].[ACTOR]
(
[ID_ACTOR] [int] NOT NULL,
[ID_DIRECTOR_ACTOR] [int] NULL,
[ID_PELICULA] [int] NULL,
[NOMBRE_ACTOR] [char] (150) COLLATE Modern_Spanish_CI_AS NULL
) ON [PRIMARY]
GO
ALTER TABLE [dbo].[ACTOR] ADD CONSTRAINT [PK_ACTOR] PRIMARY KEY CLUSTERED  ([ID_ACTOR]) ON [PRIMARY]
GO
CREATE NONCLUSTERED INDEX [RELATIONSHIP_2_FK] ON [dbo].[ACTOR] ([ID_DIRECTOR_ACTOR]) ON [PRIMARY]
GO
CREATE NONCLUSTERED INDEX [RELATIONSHIP_3_FK] ON [dbo].[ACTOR] ([ID_PELICULA]) ON [PRIMARY]
GO
ALTER TABLE [dbo].[ACTOR] ADD CONSTRAINT [FK_ACTOR_RELATIONS_DIRECTOR] FOREIGN KEY ([ID_DIRECTOR_ACTOR]) REFERENCES [dbo].[DIRECTOR_ACTOR] ([ID_DIRECTOR_ACTOR])
GO
ALTER TABLE [dbo].[ACTOR] ADD CONSTRAINT [FK_ACTOR_RELATIONS_PELICULA] FOREIGN KEY ([ID_PELICULA]) REFERENCES [dbo].[PELICULA] ([ID_PELICULA])
GO
