CREATE TABLE [dbo].[HORA_DE_PELICULA]
(
[ESTADO_RESERVA] [datetime] NOT NULL
) ON [PRIMARY]
GO
ALTER TABLE [dbo].[HORA_DE_PELICULA] ADD CONSTRAINT [PK_HORA_DE_PELICULA] PRIMARY KEY CLUSTERED  ([ESTADO_RESERVA]) ON [PRIMARY]
GO
