CREATE TABLE [dbo].[CINE]
(
[ID_CINE] [int] NOT NULL,
[NOMBRE_CINE] [text] COLLATE Modern_Spanish_CI_AS NULL,
[DIRECCION_CINE] [text] COLLATE Modern_Spanish_CI_AS NULL
) ON [PRIMARY] TEXTIMAGE_ON [PRIMARY]
GO
ALTER TABLE [dbo].[CINE] ADD CONSTRAINT [PK_CINE] PRIMARY KEY CLUSTERED  ([ID_CINE]) ON [PRIMARY]
GO
