CREATE TABLE [dbo].[CATEGORIA]
(
[ID_CATEGORIA] [int] NOT NULL,
[ID_PELICULA] [int] NULL,
[NOMBRE_CATEGORIA] [char] (150) COLLATE Modern_Spanish_CI_AS NULL
) ON [PRIMARY]
GO
ALTER TABLE [dbo].[CATEGORIA] ADD CONSTRAINT [PK_CATEGORIA] PRIMARY KEY CLUSTERED  ([ID_CATEGORIA]) ON [PRIMARY]
GO
CREATE NONCLUSTERED INDEX [RELATIONSHIP_6_FK] ON [dbo].[CATEGORIA] ([ID_PELICULA]) ON [PRIMARY]
GO
ALTER TABLE [dbo].[CATEGORIA] ADD CONSTRAINT [FK_CATEGORI_RELATIONS_PELICULA] FOREIGN KEY ([ID_PELICULA]) REFERENCES [dbo].[PELICULA] ([ID_PELICULA])
GO
